
version: '3'

services:

  apache:
    container_name: apache72
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../www:/var/www/html
      - "./wp-init.sh:/usr/local/bin/apache2-custom.sh"
    environment:
      - AMBIENTE=desarrollo
    ports:
      - "8080:80"
      - "8089:8089"
    command:
      - apache2-custom.sh
    labels:
      apache72: "Apache ambiente de DESARROLLO"


